runtime: nodejs18  # update this if your Node.js version is different
instance_class: F2  # choose an instance class based on your needs
automatic_scaling:
  target_cpu_utilization: 0.65  # adjust as necessary
  min_instances: 1  # adjust as necessary
  max_instances: 5  # adjust as necessary
env_variables:  # add your environment variables here
  NODE_ENV: 'dev'
  PORT: 8080
  INSTANCE_CONNECTION_NAME: "nest-project-391903:asia-northeast3:mysql-db01"
beta_settings:
  cloud_sql_instances: "nest-project-391903:asia-northeast3:mysql-db01"